name: 🧠 MindFlow 🌊

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: 🧹 Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black mypy
        pip install -e .

    - name: Execute Lint
      run: |
        black --check .

    - name: Execute MyPy
      run: |
        mypy --ignore-missing-imports ./

  test:
    name: 🧪 Test
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.7, 3.8, 3.9, 3.10.4]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -e .

    - name: Execute PyTest
      run: |
        pytest ./
      # Stop the workflow if any test fails
      if: ${{ job.status == 'success' }}

    outputs:
      matrix-completed: ${{ matrix.completed }}

  test-group:
    name: 🧪 Test All
    runs-on: ubuntu-latest
    needs: ${{ format('test.{0}', join(matrix.completed, ',test.')) }}
    steps:
      - name: Notify completion
        run: echo "Matrix test group completed"